import AppKit

// The menu bar indicator: the mascot, awake in colour or asleep with zZz.
// Art lives in Assets/ and is generated by tools/make-icons.py.
enum StatusIcon {
    static let canvas = NSSize(width: 18, height: 18)
    private static let inset: CGFloat = 4.5

    static func image(on: Bool) -> NSImage {
        if let art = NSImage(named: on ? "awake" : "sleep") {
            // Point size comes from the 1x representation, whose pixel size is
            // its point size by definition. Deriving it from an aspect ratio
            // instead reintroduces the rounding that knocks the art off centre.
            if let base = art.representations.min(by: { $0.pixelsHigh < $1.pixelsHigh }) {
                art.size = NSSize(width: base.pixelsWide, height: base.pixelsHigh)
            }
            // The sleep art is an alpha-only mask, so macOS tints it to match a
            // light or dark menu bar. The awake art keeps its own colour.
            art.isTemplate = !on
            return art
        }
        return drawnFallback(on: on)
    }

    /// Used only if the bundled art is missing: a plain status light.
    private static func drawnFallback(on: Bool) -> NSImage {
        let image = NSImage(size: canvas, flipped: false) { rect in
            let dot = NSBezierPath(ovalIn: rect.insetBy(dx: inset, dy: inset))
            on ? drawLit(dot) : drawDim(dot)
            return true
        }
        image.isTemplate = !on
        return image
    }

    private static func drawLit(_ dot: NSBezierPath) {
        let color = NSColor.systemGreen
        NSGraphicsContext.saveGraphicsState()

        let glow = NSShadow()
        glow.shadowColor = color.withAlphaComponent(0.9)
        glow.shadowBlurRadius = 4
        glow.shadowOffset = .zero
        glow.set()

        color.setFill()
        dot.fill()
        dot.fill()

        NSGraphicsContext.restoreGraphicsState()
    }

    private static func drawDim(_ dot: NSBezierPath) {
        NSColor.black.withAlphaComponent(0.55).setStroke()
        dot.lineWidth = 1.5
        dot.stroke()
    }
}
